version: '3.8'

services:
  api:
    build: .
    network_mode: host
    environment:
      - TASK_MGR_DB_HOST=${TASK_MGR_DB_HOST}
      - TASK_MGR_DB_PORT=${TASK_MGR_DB_PORT}
      - TASK_MGR_DB_NAME=${TASK_MGR_DB_NAME}
      - TASK_MGR_DB_LOGIN=${TASK_MGR_DB_LOGIN}
      - TASK_MGR_DB_PASSWORD=${TASK_MGR_DB_PASSWORD}
      - TASK_MGR_HOST=${TASK_MGR_HOST:-0.0.0.0}
      - TASK_MGR_PORT=${TASK_MGR_PORT:-8000}
      - TASK_MGR_BEARER=${TASK_MGR_BEARER}
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 &&
             alembic upgrade head &&
             python main.py"